export const TYPE_VALIDATION = {
  T: "T",
  R: "R",
  N: "N",
  TN: "TN",
  C: "C",
  CURP: "CURP",
  DATE: "DATE",
  EMAIL: "EMAIL",
  RFC: "RFC",
  RFC_KEY_CODE: "RFC_KEY_CODE",
  PASSWORD: "PASSWORD",
  PASSWORD_LOWERCASE: "PASSWORD_LOWERCASE",
  PASSWORD_UPPERCASE: "PASSWORD_UPPERCASE",
  PASSWORD_DIGIT: "PASSWORD_DIGIT",
  PASSWORD_SPECIAL_CHARACTER: "PASSWORD_SPECIAL_CHARACTER",
  PASSWORD_MIN: "PASSWORD_MIN",
  PASSWORD_MAX: "PASSWORD_MAX",
  PASSWORD_BLANK_SPACE: "PASSWORD_BLANK_SPACE",
  POSTAL_CODE: "POSTAL_CODE",
  SPECIAL_CHARACTER: "SPECIAL_CHARACTER",
  CUSTOM_EXP: "CUSTOM_EXP",
}

export const TYPE_LANGUAGE = {
  DEFAULT_LANGUAGE: "ES",
  EN: "EN",
  ES: "ES",
}
