export const TYPE_VALIDATION = {
  T: "T",
  R: "R",
  N: "N",
  TN: "TN",
  C: "C",
  CURP: "CURP",
  DATE: "DATE",
  EMAIL: "EMAIL",
  RFC: "RFC",
  RFC_KEY_CODE: "RFC_KEY_CODE",
  POSTAL_CODE: "POSTALCODE", // PENDIENTE
  SPECIAL_CHARACTER: "SPECIAL_CHARACTER", // PENDIENTE
}

export const TYPE_LANGUAGE = {
  DEFAULT_LANGUAGE: "ES",
  EN: "EN",
  ES: "ES",
}
